# Generated by Django 4.2.7 on 2023-11-07 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
